source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '11.0'
use_frameworks!

workspace 'MobileAnalyticsChartSwift.xcworkspace'

abstract_target 'MobileAnalyticsChartSwiftPods' do
  pod 'SwiftLint'
end